### Numpy 
##### Numpy is a fundamental library for scientific computing in Python. It provides support for arrys and matrices, along with a collection of mathematical functions to operate on these data structures. In this session, we will cover the basics of Numpy, focusing on arrays and vectorized operations.


In [2]:
!pip install numpy

In [3]:
import numpy as np

# CREATING AN ARRAY

# Create 1D array

arr1 = np.array([1,2,3,4,5]) # inside this we can give list or tuple or dict 
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr1.shape

(5,)

In [5]:
# SINGLE DIMENSION ARRAY WITH JUST [] BRACKETS
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
type(arr2)

numpy.ndarray

In [7]:
# 2D ARRAY
arr3 = np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [8]:
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [9]:
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [10]:
# start,end,step
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Identity matrix array (diagonal elements 1 and all other elements "0")

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy Vectorized Operations

In [6]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

In [11]:
#Array operations

# Element wise addition 
print("Addition:", arr1+arr2)

# Element wise substraction
print("Substraction:", arr1-arr2)

# Element wise multiplication 
print("Multiplication:", arr1 * arr2)

# Element wise division 
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [14]:
# Universal functions 
arr=np.array([1,2,3])

# sq.root
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [23]:
# Array slicing and Indexing (Index start from "0")

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
arr[0]


array([1, 2, 3, 4])

In [25]:
arr[1]

array([5, 6, 7, 8])

In [26]:
arr[2]

array([ 9, 10, 11, 12])

In [27]:
arr[0][0]

np.int64(1)

In [28]:
arr[0][1]

np.int64(2)

In [29]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [38]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr[1:4,1:3]

array([[ 6,  7],
       [10, 11]])

In [45]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [46]:
# Modify array elements 
arr[0,0] = 100

In [47]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [48]:
arr[1:]=100

In [49]:
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [55]:
# Statistical concepts - Normalization to have a mean of 0 and standard deviation of 1

data = np.array([1,2,5])

# Calculate the man and standard deviation 
mean=np.mean(data)
std_dev=np.std(data)

print(mean)
print(std_dev)

# Normalize the data 
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

# Median 
median = np.median(data)
print("Median:", median)

# Standard Deviation 
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance 
variance = np.var(data)
print("Variance:", variance)

2.6666666666666665
1.699673171197595
Normalized data: [-0.98058068 -0.39223227  1.37281295]
Median: 2.0
Standard Deviation: 1.699673171197595
Variance: 2.8888888888888893


In [56]:
# Logical operations 

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [58]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [60]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [61]:
data[(data>=5) | (data<=8)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])